- composer.json
I can't pull this in via composer because the author of the component is a jerk.
> Added package name

- docs/compatibility.md
- src/ReflectionFunctionAbstract.php
- src/ReflectionParameter.php
- src/Reflector.php
- src/TypesFinder.php
- test/Fixture/ClassForHinting.php
- test/Fixture/MethodsTest.php
- test/ReflectionParameterTest.php
As part of #7, this PR brings full compatibility with `ReflectionParameter` (where possible)
> Compatibility for ReflectionParameter

- src/TypesFinder/FindParameterType.php
- src/TypesFinder/FindTypeFromAst.php
- src/TypesFinder/ResolveTypes.php
Fixes #31. I managed to fix this without requiring #29 and #30 to be done by using a dummy context (which is what phpDocumentor does internally), which means we can fix the API early, and implement #29 and #30 independently (once this is merged at least).
> ResolveTypes invokable now requires Context always

- src/Identifier/IdentifierType.php
- src/NodeCompiler/CompileNodeToValue.php
- src/Reflector/Generic.php
- src/SourceLocator/Exception/EmptyPhpSourceCode.php
- src/SourceLocator/Exception/InvalidFileLocation.php
- src/SourceLocator/SingleFileSourceLocator.php
- src/SourceLocator/StringSourceLocator.php
- test/unit/Identifier/IdentifierTest.php
- test/unit/Identifier/IdentifierTypeTest.php
- test/unit/NodeCompiler/CompileNodeToValueTest.php
- test/unit/Reflection/ReflectionMethodTest.php
- test/unit/Reflection/ReflectionParameterTest.php
- test/unit/Reflection/ReflectionPropertyTest.php
- test/unit/Reflector/ClassReflectorTest.php
- test/unit/SourceLocator/ComposerSourceLocatorTest.php
- test/unit/SourceLocator/LocatedSourceTest.php
- test/unit/SourceLocator/SingleFileSourceLocatorTest.php
- test/unit/SourceLocator/StringSourceLocatorTest.php
- test/unit/TypesFinder/FindParameterTypeTest.php
- test/unit/TypesFinder/FindPropertyTypeTest.php
- test/unit/TypesFinder/FindTypeFromAstTest.php
- test/unit/TypesFinder/ResolveTypesTest.php
> Improve coverage #24

- docs/compatibility.md
- src/Identifier/IdentifierType.php
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionFunction.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionMethod.php
- src/Reflector/FunctionReflector.php
- src/Reflector/Generic.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflection/ReflectionFunctionTest.php
- test/unit/Reflection/ReflectionMethodTest.php
- test/unit/Reflector/FunctionReflectorTest.php
~~Depends on #32 being merged first, possibly rebase after etc.~~
This introduces compatibility for #7 items `ReflectionFunction` and `ReflectionFunctionAbstract` where possible. Some items are not implement, but marked accordingly in the compatibility list (with corresponding GitHub issues)
> Compatibility for ReflectionFunctionAbstract and ReflectionFunction

- src/Identifier/Identifier.php
- src/Identifier/IdentifierType.php
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionFunction.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflector/Generic.php
- src/SourceLocator/AutoloadSourceLocator.php
- src/SourceLocator/Exception/AutoloadFailure.php
- src/SourceLocator/Exception/FunctionUndefined.php
- src/SourceLocator/Exception/UnloadableIdentifierType.php
- test/unit/Fixture/Functions.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionFunctionTest.php
- test/unit/SourceLocator/AutoloadSourceLocatorTest.php
Implemented the `AutoloadSourceLocator` which means we can now use "static" creation of `ReflectionClass` objects, e.g.:
```php
$reflection = ReflectionClass::createFromName('BetterReflectionTest\Fixture\ExampleClass');
```
There are caveats (we expect the autoloader to load classes from a file, i.e. using require/include), but it does actually work.
~~It also means this can actually implement the `LoadSafeSourceLocator` (to be implemented)~~
Merging this would fix #36 and would be a better solution that I initially proposed actually :grinning: 
* ~~Create a `LoadSafeSourceLocator` and write the logic to do checking~~
* ~~Implement the @todo in [Identifier.php#L45](https://github.com/Roave/BetterReflection/blob/master/src/Identifier/Identifier.php#L45)~~
> Add AutoloadSourceLocator enabling ReflectionClass and ReflectionFunction instantiation

- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionFunction.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionMethod.php
- src/Reflector/Generic.php
Previously we were passing around $filename which may or may not be null or
the filename, but now we have a nicely contained LocatedSource object passed
around so we also have access to source code if we need ;)
* Required to be merged for #45
> Use LocatedSource better

- src/TypesFinder/FindParameterType.php
- test/unit/TypesFinder/FindParameterTypeTest.php
By using the better availability of `LocatedSource` from PR #44, we are able to now determine parameter types with context, thus resolving #29 
* Required for #46 to be merged
> Context for FindParameterType

- src/Reflection/ReflectionParameter.php
- src/TypesFinder/FindTypeFromAst.php
- test/unit/Reflection/ReflectionParameterTest.php
- test/unit/TypesFinder/FindTypeFromAstTest.php
By using the better availability of `LocatedSource` from PR #44, we are able to now determine parameter types with context, thus resolving #30
> Context for FindTypeFromAst

- src/TypesFinder/FindParameterType.php
- src/TypesFinder/FindPropertyType.php
- test/unit/TypesFinder/FindParameterTypeTest.php
- test/unit/TypesFinder/FindPropertyTypeTest.php
This resolves bug #5 with test cases and code updates
This also resolves bug #47
> Fix resolution of imported namespaces within docblocks in params and properties

- docs/compatibility.md
- src/Reflection/ReflectionProperty.php
- src/TypesFinder/FindPropertyType.php
- test/unit/Reflection/ReflectionPropertyTest.php
- test/unit/TypesFinder/FindPropertyTypeTest.php
As part of #7, this PR completes method compatibility for the `ReflectionProperty` class, including test coverage.
Note that the API for the `FindPropertyType` invokable has changed, because we no longer need the AST node, due to implementing the `getDocComment()` method in `ReflectionProperty`.
> Adds compatibility for ReflectionProperty

- docs/compatibility.md
- src/Reflection/Exception/MethodPrototypeNotFound.php
- src/Reflection/ReflectionMethod.php
- test/unit/Fixture/PrototypeTree.php
- test/unit/Reflection/ReflectionMethodTest.php
- test/unit/Reflection/ReflectionPropertyTest.php
Created new issue for `getPrototype()` cuz there's some janky logic there - see #57 plus we need to finish `ReflectionClass` first.
This resolves the `ReflectionMethod` item on #7.
> Pretty much compatible ReflectionMethod

- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionParameter.php
- src/Reflector/Exception/IdentifierNotFound.php
- src/Reflector/Generic.php
- test/unit/Identifier/IdentifierTest.php
- test/unit/Identifier/IdentifierTypeTest.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflection/ReflectionParameterTest.php
- test/unit/Reflector/GenericTest.php
- test/unit/SourceLocator/ComposerSourceLocatorTest.php
Merging this will resolve #24
Note that the coverage for `ReflectionClass` is already improved in #59 
The stuff that means it's not 100% quite yet is:
* PR #59 improves `Reflection` folder so is already accounted for
* There is a specific path in `Reflector\Generic` that somehow is not covered and I'm not sure why (see http://s.asgrim.com/1034bf.png)
* `NodeCompiler` this will be fixed by issue #19 so is already accounted for
> Moar test coverage

- phpunit.xml.dist
- src/Reflector/Exception/IdentifierNotFound.php
- src/Reflector/Generic.php
- src/SourceLocator/AggregateSourceLocator.php
- test/unit/Reflector/Exception/IdentifierNotFoundTest.php
- test/unit/Reflector/GenericTest.php
- test/unit/SourceLocator/AggregateSourceLocatorTest.php
Add AggregateSourceLocator which is now used internally if the source locator specified is not already an aggregate.
This fixes #53 which means in the future we can add multiple sources to source locators.
> AggregateSourceLocator for combining multiple SourceLocators

- composer.json
- composer.lock
- docs/compatibility.md
- src/Reflection/Exception/NoParent.php
- src/Reflection/Exception/NotAClassReflection.php
- src/Reflection/Exception/NotAString.php
- src/Reflection/Exception/NotAnInterfaceReflection.php
- src/Reflection/Exception/NotAnObject.php
- src/Reflection/ReflectionClass.php
- src/Reflector/Generic.php
- test/unit/Fixture/ClassWithInterfaces.php
- test/unit/Fixture/ClassesImplementingIterators.php
- test/unit/Fixture/ClassesWithCloneMethod.php
- test/unit/Fixture/ExampleClass.php
- test/unit/Fixture/InvalidInheritances.php
- test/unit/Fixture/TraitFixture.php
- test/unit/Reflection/Exception/NotAClassReflectionTest.php
- test/unit/Reflection/Exception/NotAStringTest.php
- test/unit/Reflection/Exception/NotAnInterfaceReflectionTest.php
- test/unit/Reflection/Exception/NotAnObjectTest.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflector/ClassReflectorTest.php
- test/unit/Reflector/GenericTest.php
This PR brings about "most" compatibility for `ReflectionClass`, thus merging this will finally resolve #7.
> Compatibility for ReflectionClass

- composer.json
- composer.lock
- src/NodeCompiler/CompileNodeToValue.php
- src/Reflection/ReflectionClass.php
- src/Reflector/Generic.php
- src/SourceLocator/AggregateSourceLocator.php
- src/SourceLocator/AutoloadSourceLocator.php
- src/SourceLocator/ComposerSourceLocator.php
- src/SourceLocator/EvaledCodeSourceLocator.php
- src/SourceLocator/EvaledLocatedSource.php
- src/SourceLocator/Exception/AutoloadFailure.php
- src/SourceLocator/Exception/NotInternalClass.php
- src/SourceLocator/Exception/UnloadableIdentifierType.php
- src/SourceLocator/InternalLocatedSource.php
- src/SourceLocator/LocatedSource.php
- src/SourceLocator/PhpInternalSourceLocator.php
- src/SourceLocator/SourceLocator.php
- test/unit/NodeCompiler/CompileNodeToValueTest.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/SourceLocator/AggregateSourceLocatorTest.php
- test/unit/SourceLocator/AutoloadSourceLocatorTest.php
- test/unit/SourceLocator/ComposerSourceLocatorTest.php
- test/unit/SourceLocator/EvaledCodeSourceLocatorTest.php
- test/unit/SourceLocator/EvaledLocatedSourceTest.php
- test/unit/SourceLocator/InternalLocatedSourceTest.php
- test/unit/SourceLocator/LocatedSourceTest.php
- test/unit/SourceLocator/PhpInternalSourceLocatorTest.php
This PR fixes #38
* `AggregateSourceLocator`s can be nested now (`Reflector\Generic` will recurse through them in a flat ordered way)
* I had to modify the behaviour of the `SourceLocator`s slightly so that they don't throw exceptions, but merely return null. This is so that when we loop through the `AggregateSourceLocator`, we don't break the loop.
* By default `PhpInternalSourceLocator` gets added to all calls to `reflect()`. Can be disabled by a paramter
* A new magic const is defined as a flag to notify `ReflectionClass` that the `LocatedSource` originated from the `PhpInternalSourceLocator` (thus `isInternal() === true`)
> Internal class reflections

- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflection/ReflectionPropertyTest.php
- test/unit/SourceLocator/EvaledCodeSourceLocatorTest.php
- test/unit/SourceLocator/InternalLocatedSourceTest.php
- test/unit/SourceLocator/LocatedSourceTest.php
- test/unit/SourceLocator/PhpInternalSourceLocatorTest.php
Improved coverage. There's a couple of uncovered things still:
* CompileNodeToValue - because implementation incomplete (bugs already open)
* `ClassReflector->reflect` - not sure why, the exit path seems uncovered for me, very odd o_O
* Similar thing with `Generic->reflectFromNamespace`, the parameter `LocatedSource $locatedSource` on L141 is uncovered for me
> Increase coverage again

- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionFunction.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionMethod.php
- src/Reflection/ReflectionParameter.php
- test/unit/Fixture/ExampleClassExport.txt
- test/unit/Fixture/Functions.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflection/ReflectionFunctionTest.php
- test/unit/Reflection/ReflectionMethodTest.php
- test/unit/Reflection/ReflectionParameterTest.php
- test/unit/Reflection/ReflectionPropertyTest.php
Now all `Reflection*` classes implement `\Reflector`, thus resolving #17
> Implementing reflector interface

- src/NodeCompiler/CompileNodeToValue.php
- src/NodeCompiler/CompilerContext.php
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionParameter.php
- test/unit/NodeCompiler/CompileNodeToValueTest.php
- test/unit/NodeCompiler/CompilerContextTest.php
This PR aims to solve both #64 and #19.
An alternate PR exists in #67
~~Depends on PR #96 being merged~~
> Improved node compilation in CompileNodeToValue (compile solution)

- test/unit/Reflection/ReflectionFunctionAbstractTest.php
Change node type to something that actually matches the hinted type to fix #111
(the issue was just caused because the variable passed in the test was not a `PhpParser\Node\Stmt` (was a `Scalar`) so failed the type check ^_^
> Resolve TypeError in testPopulateFunctionAbstractThrowsExceptionWithInvalidNode

- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionObject.php
- src/Reflector/ClassReflector.php
- src/Reflector/Generic.php
- src/SourceLocator/AggregateSourceLocator.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionParameterTest.php
- test/unit/Reflector/GenericTest.php
- test/unit/SourceLocator/AggregateSourceLocatorTest.php
This is a partial fix for #43
This patch disables a test, specifically `BetterReflectionTest\Reflector\GenericTest#testReflectWithAggregateSourceLocatorFindsClass()`
That test uses multiple string locators on one line.
I believe it may be up to the `StringSourceLocator` to actually filter whether a particular symbol is included in the reflected source.
The `StringSourceLocator` may internally re-use the source locator logic somehow.
> Hotfix - generic reflector should not care about locator implementation

- composer.json
the license file is available in the repo, but the info was missing in the composer.json, marking it as an unknown license on Packagist
> Add the package license for composer

- docs/features.md
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionObject.php
- src/Reflection/ReflectionParameter.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflection/ReflectionFunctionTest.php
- test/unit/Reflection/ReflectionMethodTest.php
This fixes the major breaking urgent security bug in #132
> Be consistent with capitalisation of DocBlock

- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionObject.php
- test/unit/Reflection/ReflectionClassTest.php
* enables us to get the direkt methods (like it already exists for interfaces)
* fixed the IdentifierException to be able to get the Identifier back
> added getImmediateMethods

- composer.json
The `dev-master` could change in every moment, instead the `branch-alias` shouldn’t change as fast as the previous.
> Use branch-alias instead of dev-master

- src/Reflection/Exception/Uncloneable.php
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionObject.php
- src/Reflection/ReflectionParameter.php
- src/Reflection/ReflectionProperty.php
- test/compat/ReflectionClass_CannotClone_basic.phpt
- test/unit/Reflection/Exception/Uncloneable.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflection/ReflectionObjectTest.php
- test/unit/Reflection/ReflectionParameterTest.php
- test/unit/Reflection/ReflectionPropertyTest.php
As identified in #61, the Reflections should be uncloneable...
> Make reflections uncloneable

- src/Reflection/Exception/ClassDoesNotExist.php
- src/Reflection/Exception/PropertyDoesNotExist.php
- src/Reflection/Exception/PropertyNotPublic.php
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionObject.php
- test/unit/Fixture/StaticPropertyGetSet.php
- test/unit/Reflection/ReflectionClassTest.php
As part of issue #14, this implements some stuff that requires the class to be loaded that we do not previously implement.
> Implement [g|s]etStaticPropertyValue in ReflectionClass

- README.md
- docs/ast-extraction.md
- docs/features.md
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionObject.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
Would resolve #133 and #130 
This PR adds new methods:
- `getAst` for `ReflectionClass` and `ReflectionFunctionAbstract` (#133)
- `getBodyCode` and `getBodyAst` for `ReflectionFunctionAbstract` (#130)
> Add returning AST methods

- src/SourceLocator/Type/AggregateSourceLocator.php
- test/unit/SourceLocator/Type/AggregateSourceLocatorTest.php
Hi, 
It seems the aggregate source locator was not working as `+=` ignores keys that already exist in left hand array:
> The + operator returns the right-hand array appended to the left-hand array; for keys that exist in both arrays, the elements from the left-hand array will be used, and the matching elements from the right-hand array will be ignored.
refs: http://php.net/manual/en/language.operators.array.php
> Fix locateIdentifiersByType to correctly aggregate source

- README.md
As the quality of the library is exponentially proportional to the number of the badges in the README file this is quite a drastic update.
> Drastically improved quality of library

- README.md
- demo/monkey-patching/MyClass.php
- demo/monkey-patching/index.php
- docs/reflection-modification.md
- src/Reflection/Exception/ClosureAstExtractionFailure.php
- src/Reflection/ReflectionFunctionAbstract.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
Solves part of #134  (ability to replace the statements within a function or method)
~~Note this requires PR #135 to be merged first, so do not merge please.~~
~~Also depends on jeremeamia/super_closure#70~~ (stable in 2.2.0+ now, which is used by our master now anyway)
> Method body replacement

- docs/find-reflection-on-line.md
- src/Util/FindReflectionOnLine.php
- test/unit/Fixture/FindReflectionOnLineFixture.php
- test/unit/Util/FindReflectionOnLineTest.php
Attempt number 2 and solving #178 in a nicer way.
This provides an API as per the documentation written in `docs/find-reflection-on-line.md`.
> Added FindReflectionOnLine helper utility

- README.md
- docs/features.md
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionParameter.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflection/ReflectionParameterTest.php
For feature request in issue #162, this adds feature and documentation for setting/removing PHP 7 type declarations, for both parameters and return types.
> Set/remove PHP 7 types

- src/Reflector/ClassReflector.php
- test/unit/Reflector/ClassReflectorTest.php
- test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
As reported in #189, we are creating calls on `null` objects when identifiers are not found. This is expected behaviour, but not clearly reported on. This change introduces the `IdentifierNotFound` exception, but at the `ClassReflector` level (thus allowing exception to bubble up, rather than simply returning `null`).
> Throw exceptions when ClassReflector cannot locate identifiers

- src/Reflection/ReflectionProperty.php
- test/unit/Reflection/ReflectionPropertyTest.php
Final part of #134 adds `ReflectionProperty::setVisibility()` method to change the default visibility (note; this is distinct from `setAccessible` which operates on runtime visibility)
> Added ReflectionProperty::setVisibility method

- test/unit/Reflection/ReflectionFunctionAbstractTest.php
Referring to https://github.com/nikic/PHP-Parser/releases/tag/v2.1.0 a change was introduced that distinguishes between "- and '-enclosed strings, therefore proved this test was flaky (the conversion from " to ' was assumped implicit).
> Fix unit test broken by PhpParser 2.1.0 change

- composer.json
Because `fabpot/php-cs-fixer` is moved to new package name.
> Replaced fabpot/php-cs-fixer with friendsofphp/php-cs-fixer

- test/unit/Fixture/Php7ReturnTypeDeclarations.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
Fixes #203 - `void` is already supported, so just needed to add test to ensure.
> Added test for `void` return type for PHP 7.1

- src/SourceLocator/Type/AbstractSourceLocator.php
Was still documenting the array return type.
> Fixed docblock for AbstractSourceLocator

- src/Reflection/ReflectionFunctionAbstract.php
- src/Util/Visitor/ReturnNodeVisitor.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Util/Visitor/ReturnNodeVisitorTest.php
Fixes #198 
Adds ability to fetch all `return` statement node trees from a reflection of a function/method.
> Added ReflectionFunctionAbstract::getReturnStatementsAst() method

- src/Reflection/ReflectionType.php
- src/SourceLocator/Type/EvaledCodeSourceLocator.php
- src/SourceLocator/Type/PhpInternalSourceLocator.php
These are fixes for issues found by my own static analysis tool [phpstan/phpstan](https://github.com/phpstan/phpstan). It's quite early in its development but it already proves to be really useful in my own projects. I can help you integrate it in BetterReflection if you'd like to.
By the way, there's one more error reported I wasn't sure how to fix:
```
------ ------------------------------------------------------------------------- 
Line   src/Reflection/ReflectionParameter.php                                   
------ ------------------------------------------------------------------------- 
259    Access to an undefined property PhpParser\Node\Param::$isOptional.       
------ ------------------------------------------------------------------------- 
```
It can be just a problem in a …
> Fixed issues found by static analysis

- composer.json
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionProperty.php
- src/TypesFinder/FindTypeFromAst.php
- test/unit/Reflection/ReflectionParameterTest.php
Two things blocking the merge currently:
> Update our code for API changes in PHP-Parser

- .travis.yml
- composer.json
Fixes #221 
Rebase when #217 is merged
> Require minimum of PHP 7, enabling tests on PHP 7.1

- namespace-bc-aliases.php
- src/Reflector/ClassReflector.php
- src/Reflector/FunctionReflector.php
- src/Reflector/Reflector.php
- src/SourceLocator/Exception/FunctionUndefined.php
- src/SourceLocator/Type/AutoloadSourceLocator.php
- test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
The handling in FunctionReflector was actually wrong - it was returning `null` when it should be throwing an `IdentifierNotFound` exception. In the case of using AutoloadSourceLocator when reflecting on a function, an exception `FunctionUndefined` was being thrown. This has been removed (therefore this is sadly a minor BC break) and we handle this correctly.
Fixes #234
> Fix exception being thrown in AutoloadSourceLocator

- src/Reflection/ReflectionParameter.php
- test/unit/Reflection/ReflectionParameterTest.php
> Fix `self` hinted ReflectionParameter class reference

- src/Reflection/ReflectionType.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflection/ReflectionParameterTest.php
- test/unit/Reflection/ReflectionTypeTest.php
> Fix for #243: `ReflectionType` `(string)` cast should not prepend backslash to class and interface types

- src/NodeCompiler/CompileNodeToValue.php
- test/unit/NodeCompiler/CompileNodeToValueTest.php
Class constant value referenced via `self` was not fetched properly when the constant is declared in parent class.
> Fixed class constant value fetch when constant is declared in parent

- src/NodeCompiler/CompileNodeToValue.php
- test/unit/NodeCompiler/CompileNodeToValueTest.php
Building on PR #247 - fixes test from @janlanger where `ClassConstFetch` node could not be resolved as we were not looking up the full qualified class name. Add some additional code into `CompileNodeToValue` to resolve this using the `FindTypeFromAst`.
> Constant default value failing test

- src/Reflection/ReflectionParameter.php
- test/unit/Reflection/ReflectionParameterTest.php
> create reflection parameter from closure

- docs/usage.md
It's doesn't exist anymore. Use `DirectoriesSourceLocator` instead
> [Docs] Usage: drop SingleDirectorySourceLocator

- src/SourceLocator/Type/AutoloadSourceLocator.php
- test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
Fixes #237 
Now that we have strict type declarations, I don't think an additional test is necessary - this is essentially a bugfix now IMO...
> Ensure locateFunctionByName returns ?string always

- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionObject.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionObjectTest.php
> Filter get methods and properties

- src/NodeCompiler/CompileNodeToValue.php
- src/NodeCompiler/CompilerContext.php
- test/unit/Fixture/ExampleClass.php
- test/unit/NodeCompiler/CompileNodeToValueTest.php
- test/unit/NodeCompiler/CompilerContextTest.php
- test/unit/Reflection/ReflectionClassTest.php
Parser is failing at the moment on misisng NodeCompiler for `__DIR__`:
```php
class ConstantInClass
{
/**
* @var string
*/
protected const COMPOSED_WITH_DIR = __DIR__ . '/here';
}
```
This PR fixes it. Test included.
> [NodeCompiler] add support for __DIR__

- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionProperty.php
- src/Util/GetFirstDocComment.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflection/ReflectionPropertyTest.php
- test/unit/Util/GetFirstDocCommentTest.php
Before this, it could happen that comment returned is not really instance of `\PhpParser\Comment\Doc` but just instance of an ordinary comment.
> fixed improper docblock retrieval

- docs/reflection-modification.md
Quick fix: adding the new Roave namespace to the `reflection-modification.md` page
> Documentation fix regarding new Roave namespace

- src/Reflection/Adapter/ReflectionClass.php
- src/Reflection/Adapter/ReflectionClassConstant.php
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionClassConstant.php
- src/Reflection/ReflectionObject.php
- test/unit/Fixture/ExampleClass.php
- test/unit/Fixture/ExampleClassExport.txt
- test/unit/Reflection/Adapter/ReflectionClassConstantTest.php
- test/unit/Reflection/Adapter/ReflectionClassTest.php
- test/unit/Reflection/ReflectionClassConstantTest.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionObjectTest.php
https://github.com/Roave/BetterReflection/issues/281 
Note: I did not understand how testReflectionObjectOverridesAllMethodsInReflectionClass works, therefore I missed it.
> [PHP 7.1] Add support for ReflectionClassConstant (#281)

- composer.json
- src/Reflection/ReflectionParameter.php
- test/unit/TypesFinder/FindParameterTypeTest.php
- test/unit/TypesFinder/ResolveTypesTest.php
Fixes #202 
Fixes #242 
Adds support for these new types, but TypesResolver needs a new release (that doesn't conflict with `phpdocumentor/reflection-docblock` - `phpdocumentor/reflection-docblock 3.1.1 requires phpdocumentor/type-resolver ^0.2.0 -> satisfiable by phpdocumentor/type-resolver[0.2, 0.2.1] but these conflict with your requirements or minimum-stability.`) before we can merge really :/
> Added test cases for ?nullable and iterable types in PHP 7.1

- README.md
- src/Reflection/ReflectionParameter.php
- src/Reflection/ReflectionProperty.php
- test/unit/Reflection/ReflectionParameterTest.php
- test/unit/Reflection/ReflectionPropertyTest.php
* Removes `ReflectionProperty->getDefaultValueAsString()`
* Deprecates `ReflectionParameter->getDefaultValueAsString()`
> getDefaultValueAsString removals/deprecation

- src/Reflection/ReflectionParameter.php
- test/unit/Fixture/Methods.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionParameterTest.php
With code style using uppercased `TRUE`, `FALSE` and `NULL`, the condition did not work.
> ReflectionParameter::parseDefaultValueNode() - case insensitive check of TRUE, FALSE and NULL

- src/Reflection/ReflectionParameter.php
- test/unit/Fixture/ClassWithConstantsAsDefaultValues.php
- test/unit/Reflection/ReflectionParameterTest.php
In short: `AClass::SOME` !== `BClass::SOME` !== `SOME`
In reflection of this method
```php
public function method($param1 = AClass::SOME, $param2 = BClass::SOME);
```
method `getDefaultValueConstantName()` cannot return just `SOME` for it is not precise description of what constant it really is.
> ReflectionParameter: return full name if default value is class' constant

- .travis.yml
- composer.json
- src/Reflection/Adapter/ReflectionClass.php
- src/Reflection/Adapter/ReflectionObject.php
Fix of https://github.com/Roave/BetterReflection/issues/317
Inspired by https://github.com/goaop/parser-reflection/issues/70
> ReflectionClass::newInstance() and ReflectionObject::newInstance() compatibility in all PHP versions

- src/Identifier/Exception/InvalidIdentifierName.php
- src/Identifier/Identifier.php
- src/SourceLocator/Type/AbstractSourceLocator.php
- test/unit/Identifier/Exception/InvalidIdentifierNameTest.php
- test/unit/Identifier/IdentifierTest.php
Implemented https://github.com/Roave/BetterReflection/issues/20
I've slightly modifed the regexp:
Before: `/([a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]+)(\\\\[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]+)*/`
After:  `'/([a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*)(\\\\[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*)*/'`
The first one did not support names with only one letter.
> Check if identifier name is valid

- README.md
- composer.json
- phpstan.neon
- src/SourceLocator/Reflection/SourceStubber.php
- src/SourceLocator/Type/EvaledCodeSourceLocator.php
- src/SourceLocator/Type/PhpInternalSourceLocator.php
- test/unit/Fixture/ClassForSourceStubber.php
- test/unit/Fixture/ClassForSourceStubberExpected.php
- test/unit/Fixture/ClassWithoutNamespaceForSourceStubber.php
- test/unit/Fixture/ClassWithoutNamespaceForSourceStubberExpected.php
- test/unit/Fixture/InterfaceForSourceStubber.php
- test/unit/Fixture/InterfaceForSourceStubberExpected.php
- test/unit/Fixture/TraitForSourceStubber.php
- test/unit/Fixture/TraitForSourceStubberExpected.php
- test/unit/SourceLocator/Reflection/SourceStubberTest.php
There's already PhpParser so we can use its `BuilderFactory` to remove dependency on `zendframework/zend-code`.
It should be probably a little faster too because this code has been removed: https://github.com/Roave/BetterReflection/blob/master/src/SourceLocator/Reflection/SourceStubber.php#L51
> `PhpParser\BuilderFactory` instead of `Zend\Code\Generator\ClassGenerator` in the `SourceStubber`

- composer.json
- test/unit/Fixture/TraitForSourceStubber.php
- test/unit/Fixture/TraitForSourceStubberExpected.php
There was a bug in php-parser 3.1.0. It's fixed in [3.1.1](https://github.com/nikic/PHP-Parser/releases/tag/v3.1.1) so it's possible to improve one test.
> Improved SourceStubber trait tests

- src/Reflection/ReflectionMethod.php
- src/Reflection/ReflectionProperty.php
Just hunting for static analysis issues. 7.2 will make this more pleasant in the future.
> Replacing internal `assertObject` return type with `object`, removing therefore the implicit upcast

- stub/UConverter.stub
- test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
This patch updates the stub and prevents testing of the parameter on older PHP versions.
Ref https://github.com/php/php-src/commit/ec3d864784aa14187ca20a7644ee78c813d8b744
Ref https://bugs.php.net/bug.php?id=75318
> #379 `UConverter#getAliases($name)` is not an optional parameter anymore as per latest PHP releases

- src/Reflection/ReflectionFunctionAbstract.php
- test/unit/Fixture/InterfaceWithMethod.php
- test/unit/Reflection/ReflectionMethodTest.php
Fixes: #378 
Problem is caused when inspecting method of an interface. See also https://github.com/nikic/PHP-Parser/issues/235#issuecomment-194505139
> Return empty ast for interface method body

- docs/types.md
rename $myMethod to $myParameter as expected by getParameter('myParameter')
> Fix wrong parameter name

- UPGRADE.md
- src/Reflection/Exception/ClassDoesNotExist.php
- src/Reflection/Exception/ReflectionTypeDoesNotPointToAClassAlikeType.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionParameter.php
- src/Reflection/ReflectionType.php
- test/compat/ResolvePHP7Types.phpt
- test/unit/Reflection/Adapter/ReflectionTypeTest.php
- test/unit/Reflection/Exception/ClassDoesNotExistTest.php
- test/unit/Reflection/Exception/ReflectionTypeDoesNotPointToAClassAlikeTypeTest.php
- test/unit/Reflection/ReflectionTypeTest.php
Required for https://github.com/Roave/ApiCompare/pull/38
> Improved `ReflectionType` API so that a target reflection class can be found, removed existing named constructor

- src/SourceLocator/Ast/Locator.php
- test/unit/SourceLocator/Ast/LocatorTest.php
The PR is a bit incomplete (missing tests) but it's more for myself to not forget about it :)
The issue is that [PHP is case insensitive](https://3v4l.org/SYNgh) for namespaces, classes and methods. However BetterReflection does not account for that as a result if you have:
```php
use PHAR;
```
Instead of:
```php
use Phar;
```
BetterReflection is going to fail.
> Account for case insensitivity

- src/NodeCompiler/CompileNodeToValue.php
- src/NodeCompiler/Exception/UnableToCompileNode.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/TypesFinder/FindParameterType.php
- test/unit/NodeCompiler/CompileNodeToValueTest.php
- test/unit/NodeCompiler/Exception/UnableToCompileNodeTest.php
This basically replaces a null pointer error with a nicer exception with some
minimal context/description around it.
> Better exception messages and assertions for unrecognized class constant fetch expressions

- src/Reflection/ReflectionClass.php
- test/unit/Fixture/AnonymousClassInstanceWithInterface.php
- test/unit/Reflection/ReflectionObjectTest.php
should i send the same fix for v2?
> Fixed error on anonymous classes with interfaces

- .travis.yml
- phpstan.neon
- src/SourceLocator/Type/AutoloadSourceLocator.php
- test/unit/Fixture/AutoloadableClassWithTwoDirectories.php
- test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
This PR fixes #384.
The issue was that Composer autoloader is scanning the PSR-4 directories that may contain the file.
**Composer's ClassLoader.php excerpt**:
```php
foreach ($this->prefixDirsPsr4[$search] as $dir) {
if (file_exists($file = $dir . $pathEnd)) {
return $file;
}
}
```
The call to `file_exists` was always returning `true`, because of the way the `AutoloadSourceLocator::url_stat` was written.
I reimplemented the `url_stat` to actually unregister the stream wrapper, fall back to the real stream wrapper, do the real "stat" call and then re-register the stream wrapper.
The code is strongly inspired from PHP-VCR so thanks to PHP-VCR folks for the idea :)
Note: The first commit is a failing test to demonstrate #384 issue.
> Fixing AutoloadSourceLocator when multiple PSR-0/4 directories are possible

- src/Reflection/Adapter/ReflectionClass.php
- test/unit/Reflection/Adapter/ReflectionClassTest.php
As per https://secure.php.net/manual/en/reflectionclass.getconstructor.php. If someone can guide me on how to write a test for this, I'll be happy to do it.
> Adapter's ReflectionClass::getConstructor() returns null when no constructor exists

- .travis.yml
- composer.json
- composer.lock
- src/SourceLocator/Reflection/SourceStubber.php
- stub/SoapServer.stub
- test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
This should fix #440.
One parameter definition has changed, I just followed what has been done for PHP 7.1 => PHP 7.2 and updated the stub to comply with PHP 7.3 definition.
> Php 7.3 tests

- .gitignore
- test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
The previous version of `.gitignore` does not work on Windows.
> Fix `.gitignore` format for Windows environments

- test/unit/Reflection/Adapter/ReflectionClassConstantTest.php
- test/unit/Reflection/Adapter/ReflectionClassTest.php
- test/unit/Reflection/Adapter/ReflectionFunctionTest.php
- test/unit/Reflection/Adapter/ReflectionMethodTest.php
- test/unit/Reflection/Adapter/ReflectionObjectTest.php
- test/unit/Reflection/Adapter/ReflectionParameterTest.php
- test/unit/Reflection/Adapter/ReflectionPropertyTest.php
- test/unit/Reflection/Adapter/ReflectionTypeTest.php
- test/unit/Reflector/ClassReflectorTest.php
- test/unit/Reflector/FunctionReflectorTest.php
- test/unit/SourceLocator/Ast/FindReflectionsInTreeTest.php
- test/unit/SourceLocator/Ast/Parser/MemoizingParserTest.php
- test/unit/SourceLocator/Ast/Strategy/NodeToReflectionTest.php
- test/unit/SourceLocator/Type/AbstractSourceLocatorTest.php
- test/unit/SourceLocator/Type/AggregateSourceLocatorTest.php
- test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
- test/unit/SourceLocator/Type/ComposerSourceLocatorTest.php
- test/unit/SourceLocator/Type/EvaledCodeSourceLocatorTest.php
- test/unit/SourceLocator/Type/MemoizingSourceLocatorTest.php
- test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
- test/unit/SourceLocator/Type/SingleFileSourceLocatorTest.php
- test/unit/SourceLocator/Type/StringSourceLocatorTest.php
- test/unit/TypesFinder/FindParameterTypeTest.php
- test/unit/TypesFinder/FindPropertyTypeTest.php
- test/unit/TypesFinder/FindReturnTypeTest.php
- test/unit/Util/Autoload/ClassLoaderMethod/FileCacheLoaderTest.php
- test/unit/Util/Autoload/ClassLoaderTest.php
- test/unit/Util/Autoload/Exception/ClassAlreadyLoadedTest.php
- test/unit/Util/Autoload/Exception/ClassAlreadyRegisteredTest.php
Broken since https://github.com/Roave/BetterReflection/commit/b9a4c135809d1295325e3e819b18414f42ac793e
> Correct PHPUnit MockObject class names as per PHPUnit 8+

- test/unit/SourceLocator/SourceStubber/AggregateSourceStubberTest.php
- test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
As mentioned in https://github.com/Roave/BetterReflection/pull/373
> Tests for source stubbers

- src/NodeCompiler/CompileNodeToValue.php
- test/unit/NodeCompiler/CompileNodeToValueTest.php
Fixes https://github.com/Roave/BetterReflection/issues/444
>  Fixed resolving self::, static:: and parent:: as property or constant values

- UPGRADE.md
- src/Reflection/Adapter/ReflectionClass.php
- src/Reflection/Adapter/ReflectionFunction.php
- src/Reflection/Adapter/ReflectionMethod.php
- src/Reflection/Adapter/ReflectionObject.php
- src/Reflection/Adapter/ReflectionParameter.php
- src/Reflection/Adapter/ReflectionProperty.php
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionClassConstant.php
- src/Reflection/ReflectionConstant.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionObject.php
- src/Reflection/ReflectionParameter.php
- src/Reflection/ReflectionProperty.php
- test/unit/Reflection/Adapter/ReflectionClassTest.php
- test/unit/Reflection/Adapter/ReflectionObjectTest.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionConstantTest.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
- test/unit/Reflection/ReflectionFunctionTest.php
- test/unit/Reflection/ReflectionMethodTest.php
- test/unit/Reflection/ReflectionObjectTest.php
- test/unit/Reflection/ReflectionParameterTest.php
- test/unit/Reflection/ReflectionPropertyTest.php
Replaces #397 from @muglug - I've rebased onto latest `master`, and implemented the proposal.
Note: introduces a BC break, so definitely targeting 4.0.0 for this.
> Fix behaviour of ReflectionClass::export/ReflectionObject::export to match behaviour of core classes

- test/unit/Reflection/Adapter/ReflectionMethodTest.php
It was returning a `bool(false)` previously, which technically is fine (returns `false` if no comment exists), but I guess it makes more sense to return a string anyway because that's the usual case if a doc does exist anyway.
> Make getDocComment in adapter test return a string

- composer.json
- composer.lock
This PR updates `composer.json` to allow usage of `phpdocumentor/type-resolver` with version `^1.0.0`.
It also updates `composer.lock` for those new dependencies (but in my opinion, `composer.lock` should not be committed for a package).
> Allow phpdocumentor/type-resolver version ^1.0.0

- .travis.yml
This effectively restricts CI on push to branch or tags only.
> Run CI only once on PR from another branch of the repo

- src/Reflection/ReflectionClass.php
- test/unit/Fixture/ExampleClass.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflector/ClassReflectorTest.php
It looks @ondrejmirtes is too lazy to send PR 😛
> ReflectionClass::getConstructor() should work event if the constructor isn't the first method in the class

- src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJson.php
- src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
- src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
As discussed here  #525 I described some types to improve Psalm coverage from 98.9751% to 99.2148%
This is not very elegant but I don't see a better way without refactoring the code just to pass smaller chunks of the whole file.
> Improve Psalm coverage for decoded datas from json files

- composer.lock
I suspect that the dependencies has been updated with a higher PHP version than `7.2.0`, our minimal supported PHP version.
> Fix dependencies installation

- psalm.xml
- src/NodeCompiler/CompileNodeToValue.php
- src/Reflection/Adapter/ReflectionClass.php
- src/Reflection/Adapter/ReflectionClassConstant.php
- src/Reflection/Adapter/ReflectionObject.php
- src/Reflection/Exception/NotAnObject.php
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionClassConstant.php
- src/Reflection/ReflectionConstant.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionObject.php
- src/Reflection/ReflectionParameter.php
- src/Reflection/ReflectionProperty.php
- src/Reflection/StringCast/ReflectionClassConstantStringCast.php
- src/Reflection/StringCast/ReflectionConstantStringCast.php
- src/SourceLocator/Ast/FindReflectionsInTree.php
- src/SourceLocator/Ast/Locator.php
- src/SourceLocator/Exception/InvalidDirectory.php
- src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
- src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
- src/SourceLocator/Type/Composer/Psr/PsrAutoloaderMapping.php
- src/Util/GetFirstDocComment.php
This is a draft PR with the changes I made for #525 to see the rest of the CI and to discuss about some changes
The increase in type coverage is disappointing because a lot of mixed types still comes from outside.
Still, the changes prepare the way for when 
https://github.com/nikic/PHP-Parser/pull/647
and
https://github.com/vimeo/psalm/pull/2612
will be merged.
> add psalm types

- psalm-baseline.xml
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/SourceLocator/Ast/FindReflectionsInTree.php
- src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
- src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
- src/SourceLocator/Type/AutoloadSourceLocator.php
- src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
- src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
- test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
- test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
I fixed some errors, updated baseline.
It improved type coverage a bit.
> various improvements for psalm

- composer.json
- composer.lock
- psalm-baseline.xml
- psalm.xml
- src/NodeCompiler/Exception/UnableToCompileNode.php
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionFunction.php
- src/Reflection/ReflectionProperty.php
- src/Reflector/ClassReflector.php
- src/TypesFinder/ResolveTypes.php
- src/Util/GetFirstDocComment.php
Bumping psalm on last version to use usePhpDocPropertiesWithoutMagicCall.
This allows to drop some ignored errors and gain some type coverage.
Also fixed some errors
> bump psalm, fix errors, add usePhpDocPropertiesWithoutMagicCall

- .travis.yml
- composer.json
- composer.lock
This PR bump phpbench to solve CI error we get on #547 . It also bumps phpstan to 0.12.11 version so we can stop bothering Ondřej Mirtes on #538 :)
The SA errors are unrelated and fixed in #547 anyway.
> bump phpbench and phpstan

- src/NodeCompiler/Exception/UnableToCompileNode.php
- test/unit/NodeCompiler/Exception/UnableToCompileNodeTest.php
> Enhancement: Allow fetching constant name from exception

- composer.json
- composer.lock
- src/Reflection/Adapter/ReflectionClass.php
- src/Reflection/Adapter/ReflectionObject.php
- src/Reflection/Adapter/ReflectionProperty.php
- src/Util/GetFirstDocComment.php
Fixes #568 
Potentially a BC break, but I would rather say that here `BetterReflection` is not respecting the types inherited from `ext-reflection`.
@asgrim can I please have your opinion on this? Should I release it under `4.x`, or push `5.0.0`? I'm inclined to call it a `4.x` problem (since we don't control the type)
> Align adapter types to ext reflection collection-ish method types

- src/Reflection/ReflectionClass.php
- test/unit/Fixture/ClassWithMissingParent.php
- test/unit/Reflection/ReflectionClassTest.php
It should cache only when all methods are processed.
Credit goes to @ondrejmirtes
> Fixed methods cache in ReflectionClass

- .github/workflows/build.yml
HT to @ondrejmirtes who suggested that for #585 to build in the PR, the `master` branch needs already GH actions enabled. So this adds this.
> Add hello world github action for #585 to base off

- src/Reflection/Adapter/ReflectionMethod.php
- test/unit/Reflection/Adapter/ReflectionMethodTest.php
> Fixed ReflectionMethod::isAbstract() in adapter

- psalm.xml
This PR removes some suppressed errors in psalm.xml.
Those errors seem to not exists anymore, so this will prevent new similar errors to be introduced in future commits.
> Psalm.xml cleanup

- src/Reflection/Adapter/ReflectionMethod.php
- src/Reflection/ReflectionMethod.php
- test/unit/Reflection/Adapter/ReflectionMethodTest.php
- test/unit/Reflection/ReflectionMethodTest.php
> ReflectionMethod::isAbstract() should return true for interface methods

- src/Reflection/Adapter/ReflectionClass.php
- src/Reflection/ReflectionClass.php
- test/unit/Fixture/ClassWithCaseInsensitiveMethods.php
- test/unit/Reflection/Adapter/ReflectionClassTest.php
- test/unit/Reflection/ReflectionClassTest.php
> Methods are case insensitive, and should be mapped and looked up without considering casing

- phpcs.xml.dist
- src/SourceLocator/Type/AutoloadSourceLocator.php
- src/SourceLocator/Type/AutoloadSourceLocator/FileReadTrapStreamWrapper.php
- test/unit/SourceLocator/Type/AutoloadSourceLocator/FileReadTrapStreamWrapperTest.php
- test/unit/SourceLocator/Type/AutoloadSourceLocatorTest.php
- test/unit/SourceLocator/Type/AutoloadSourceLocatorWithoutLoadedParserDependenciesTest.php
Fixes #573
Fixes #575
Removed stream wrapper logic from `AutoloadSourceLocator`: using the new `FileReadTrapStreamWrapper` for that
This simplifies the `AutoloadSourceLocator` massively:
* the constructor no longer needs to be zero-arguments (although not changed that, for BC compliance)
* internal state slimmed down
* magic around the object is "mostly" gone
* allows using custom AST locators internally
> #573 ensure `AutoloadSourceLocator` does not interfere with autoloading of PHP-Parser nor BetterReflection internals

- test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
- test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
- test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
> Verify `ReflectionSourceStubber` and `PhpInternalSourceLocator`  against `FFI`, `memcache`, `mongodb` and `redis` extension symbols

- phpstan.neon
This solves problem mentioned in https://github.com/Roave/BetterReflection/pull/606#issuecomment-634989856
This is already optimized in dev-master but it will take some time for me to implement rules that we lose by starting using static reflection and release 0.12.26 so it's a good idea to do this meanwhile.
> Exclude PhpStormStubsSourceStubber temporarily from the PHPStan analysis

- src/Reflection/Adapter/ReflectionClass.php
- src/Reflection/Adapter/ReflectionObject.php
- test/unit/Reflection/Adapter/ReflectionClassTest.php
- test/unit/Reflection/Adapter/ReflectionObjectTest.php
> Fixed `ReflectionClass::isInstance()` adapter compatibility with native reflection

- phpcs.xml.dist
- src/NodeCompiler/CompileNodeToValue.php
- src/Reflection/Adapter/ReflectionClass.php
- src/Reflection/Adapter/ReflectionClassConstant.php
- src/Reflection/Adapter/ReflectionObject.php
- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionClassConstant.php
- src/Reflection/ReflectionConstant.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionObject.php
- src/Reflection/ReflectionParameter.php
- src/Reflection/ReflectionProperty.php
- src/SourceLocator/Ast/FindReflectionsInTree.php
- src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
- src/SourceLocator/SourceStubber/ReflectionSourceStubber.php
- src/SourceLocator/Type/AutoloadSourceLocator.php
- src/SourceLocator/Type/AutoloadSourceLocator/FileReadTrapStreamWrapper.php
- src/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJson.php
- src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
- src/SourceLocator/Type/Composer/Psr/PsrAutoloaderMapping.php
- test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php
- test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerInstalledJsonTest.php
- test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonAndInstalledJsonTest.php
- test/unit/SourceLocator/Type/Composer/Factory/MakeLocatorForComposerJsonTest.php
- test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php
PHPCS (thanks to Slevomat CS), PHPStan and Psalm can parse standard annotations even with extended syntax so I think we can use less specific `@psalm` annotations.
> Annotations cleanup

- src/Reflection/Adapter/ReflectionClass.php
- test/unit/Reflection/Adapter/ReflectionClassTest.php
> Fixed ReflectionClass::getReflectionConstant() in adapter for non-existent constant

- src/Reflection/ReflectionClass.php
- src/Reflection/ReflectionClassConstant.php
- src/Reflection/ReflectionConstant.php
- src/Reflection/ReflectionFunctionAbstract.php
- src/Reflection/ReflectionParameter.php
- src/Reflection/ReflectionProperty.php
- src/Util/CalculateReflectionColumn.php
- test/unit/Util/CalculateReflectionColumnTest.php
There is already `CalculateReflectionColumnTest` (spelled correctly) that should provide test coverage for this typo fix of the class name.
> Fix name of CalculateReflectionColumn class

- docs/usage.md
- src/SourceLocator/Type/AutoloadSourceLocator.php
- test/unit/Fixture/ClassesWithPublicOrNonPublicConstructor.php
- test/unit/Reflection/Adapter/ReflectionPropertyTest.php
- test/unit/Reflection/ReflectionClassConstantTest.php
- test/unit/Reflection/ReflectionClassTest.php
- test/unit/Reflection/ReflectionPropertyTest.php
- test/unit/SourceLocator/Ast/LocatorTest.php
- test/unit/SourceLocator/SourceStubber/ReflectionSourceStubberTest.php
- test/unit/SourceLocator/Type/MemoizingSourceLocatorTest.php
Typo changes are only in docs, code comments, and tests. So should be no run-time effect here.
> Fix minor typos

- src/Reflection/ReflectionClass.php
- test/unit/Fixture/PrototypeTree.php
- test/unit/Reflection/ReflectionClassTest.php
> Fixed `ReflectionClass::getImmediateInterfaces()` to only return immediately implemented interfaces

- src/Reflection/ReflectionFunctionAbstract.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
> Fixed `Reflection/ReflectionFunctionAbstract::isGenerator()` for functions with `yield from`

- src/Reflection/ReflectionMethod.php
- test/unit/Fixture/PrototypeTree.php
- test/unit/Reflection/ReflectionMethodTest.php
> `ReflectionMethod::getPrototype()` should report implementing vlass prototype, and skip constructors

- src/Util/FileHelper.php
- test/unit/Util/FileHelperTest.php
Previously it generated path with `phar:\\...`.
> FileHelper - fix normalizing paths with protocol:// on Windows

- src/SourceLocator/Ast/Parser/MemoizingParser.php
- src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
- test/unit/SourceLocator/Ast/Parser/MemoizingParserTest.php
> Reduce memory footprint of `PhpStormStubsSourceStubber` and `MemoizingParser`

- src/Reflection/ReflectionClass.php
- test/unit/Fixture/MethodsOrder.php
- test/unit/Fixture/TraitFixture.php
- test/unit/Fixture/TraitWithAbstractMethod.php
- test/unit/Reflection/ReflectionClassTest.php
Fixes #647 
Fixes #659
Also fixes methods order: https://3v4l.org/LiTi4
> Corrected trait analysis: method ordering, abstract trait methods do not override concrete ones, method aliases now recognized

- src/Reflection/ReflectionClass.php
- test/unit/Fixture/MethodsOrder.php
- test/unit/Fixture/TraitFixture.php
- test/unit/Fixture/TraitWithAbstractMethod.php
- test/unit/Reflection/ReflectionClassTest.php
Release [4.6.1](https://github.com/Roave/BetterReflection/milestone/29)
4.6.1
=====
- Total issues resolved: **2**
- Total pull requests resolved: **1**
- Total contributors: **2**
bug
---
- [652: Corrected trait analysis: method ordering, abstract trait methods do not override concrete ones, method aliases now recognized](https://github.com/Roave/BetterReflection/pull/652) thanks to @kukulich and @ondrejmirtes
> Merge release 4.6.1 into master

- src/Reflection/ReflectionFunctionAbstract.php
- test/unit/Reflection/ReflectionFunctionAbstractTest.php
Related:
* fixes #38 
* https://github.com/phpstan/phpstan-deprecation-rules/issues/24
> Allow functions to be deprecated

- src/Reflection/ReflectionParameter.php
- test/unit/Reflection/ReflectionParameterTest.php
For example, this function ```function foo(int $case = \CASE_LOWER);```, ReflectionParameter->allowsNull() for ```$case```will currently return ```true```.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/roave/betterreflection/678)
> ReflectionParameter: try to get the correct default value for constants
