docs/compatibility.md

Related to #7, this provides explanation as to why some functionality is not implemented

Added short messages that explain why some functionality will not be available

---

CONTRIBUTING.md
LICENSE
README.md
docs/features.md
docs/types.md
docs/usage.md

Updating documentation a lot

---

src/NodeCompiler/CompileNodeToValue.php
test/unit/NodeCompiler/CompileNodeToValueTest.php

Merging this should resolve #51

Compile array expressions in CompileNodeToValue

---

src/SourceLocator/LocatedSource.php
test/unit/SourceLocator/LocatedSourceTest.php

Add validation that file is valid in LocatedSource constructor

---

src/Reflection/ReflectionClass.php
test/unit/Fixture/ClassWithInterfaces.php
test/unit/Reflection/ReflectionClassTest.php

`ReflectionClass#getInterfaces()` and `ReflectionClass#getInterfaceNames()` support

---

src/Reflection/Exception/NotAnObject.php
src/Reflection/ReflectionClass.php
test/unit/Reflection/Exception/NotAnObjectTest.php
test/unit/Reflection/ReflectionClassTest.php

`ReflectionClass#isInstance()` support

---

src/Reflection/Exception/NotAString.php
src/Reflection/ReflectionClass.php
test/unit/Reflection/Exception/NotAStringTest.php
test/unit/Reflection/ReflectionClassTest.php

`ReflectionClass#isSubclassOf()` support

---

src/Reflection/ReflectionClass.php
test/unit/Reflection/ReflectionClassTest.php

`ReflectionClass#implementsInterface()` support

---

phpunit.xml.dist
test/unit/TestListener.php

Added test listener that ensure classes do not get loaded during tests

---

composer.json
composer.lock
src/NodeCompiler/CompileNodeToValue.php
src/Reflection/ReflectionClass.php
src/Reflector/Generic.php
src/SourceLocator/EvaledCodeSourceLocator.php
src/SourceLocator/EvaledLocatedSource.php
src/SourceLocator/InternalLocatedSource.php
src/SourceLocator/LocatedSource.php
src/SourceLocator/PhpInternalSourceLocator.php
test/unit/NodeCompiler/CompileNodeToValueTest.php
test/unit/Reflection/ReflectionClassTest.php
test/unit/SourceLocator/EvaledCodeSourceLocatorTest.php
test/unit/SourceLocator/EvaledLocatedSourceTest.php
test/unit/SourceLocator/InternalLocatedSourceTest.php
test/unit/SourceLocator/LocatedSourceTest.php
test/unit/SourceLocator/PhpInternalSourceLocatorTest.php

Because.
https://www.youtube.com/watch?v=GAvS1ndtEKg

Internal class reflections runtime stubbing

---

src/Reflection/ReflectionProperty.php
test/unit/TypesFinder/FindPropertyTypeTest.php

Part of #34 - this PR makes `ReflectionProperty` load "lazily"

Made ReflectionProperty load lazily

---

src/Reflection/ReflectionFunctionAbstract.php

Az part of #34 this introduces some really lazy loading to `ReflectionFunctionAbstract`

Refactored ReflectionFunctionAbstract to be super lazy

---

src/Reflection/ReflectionClass.php
src/Reflection/ReflectionMethod.php
test/unit/Fixture/PrototypeTree.php
test/unit/Reflection/ReflectionClassTest.php
test/unit/Reflection/ReflectionMethodTest.php

This fixes #57 by implementing `ReflecitonMethod::getPrototype()`

Implement ReflectionMethod::getPrototype()

---

src/Reflection/ReflectionParameter.php

Refactored ReflectionParameter to be lazy

---

src/Reflection/ReflectionClass.php

Final piece of the lazy loading - this introduces lazy-reflection for `ReflectionClass` for #34

Lazy ReflectionClass

---

src/Reflection/ReflectionFunctionAbstract.php
src/Reflection/ReflectionMethod.php
test/unit/Reflection/ReflectionMethodTest.php

As part of #34, this implements lazy reflection for `ReflectionMethod`

Implemented lazy style for ReflectionMethod

---

docs/compatibility.md
docs/usage.md
src/SourceLocator/SourceLocator.php

Update with changes from PRs #59, #81, #80, #78

Updated documentation to reflect recent changes

---

src/Reflection/ReflectionClass.php
src/Reflection/ReflectionObject.php
src/Reflection/ReflectionProperty.php
src/SourceLocator/EvaledLocatedSource.php
test/unit/Fixture/ClassForHinting.php
test/unit/Reflection/ReflectionObjectTest.php

Fixes #16 by implementing `ReflectionObject` which can reflect run-time properties.

ReflectionObject

---

docs/compatibility.md
src/Reflection/ReflectionClass.php
src/Reflection/ReflectionFunction.php
src/Reflection/ReflectionFunctionAbstract.php
src/Reflection/ReflectionMethod.php
src/Reflection/ReflectionObject.php
src/Reflection/ReflectionParameter.php
src/Reflection/ReflectionProperty.php
src/Reflector/Generic.php
test/unit/Reflection/ReflectionFunctionAbstractTest.php
test/unit/Reflection/ReflectionParameterTest.php

Fixes issue #13 by implementing `ReflectionParameter::getClass()` method

Added ReflectionParameter->getClass() method

---

src/NodeCompiler/CompileNodeToValue.php
test/unit/NodeCompiler/CompileNodeToValueTest.php

Evaluate the value of already-existing constants

---

docs/compatibility.md
phpunit.xml.dist
src/Reflection/Adapter/Exception/NotImplemented.php
src/Reflection/Adapter/ReflectionClass.php
src/Reflection/Adapter/ReflectionFunction.php
src/Reflection/Adapter/ReflectionMethod.php
src/Reflection/Adapter/ReflectionObject.php
src/Reflection/Adapter/ReflectionParameter.php
src/Reflection/Adapter/ReflectionProperty.php
src/Reflection/ReflectionClass.php
src/Reflection/ReflectionObject.php
src/Reflection/ReflectionProperty.php
test/unit/Fixture/DefaultProperties.php
test/unit/Reflection/Adapter/ReflectionClassTest.php
test/unit/Reflection/Adapter/ReflectionFunctionTest.php
test/unit/Reflection/Adapter/ReflectionMethodTest.php
test/unit/Reflection/Adapter/ReflectionObjectTest.php
test/unit/Reflection/Adapter/ReflectionParameterTest.php
test/unit/Reflection/Adapter/ReflectionPropertyTest.php
test/unit/Reflection/ReflectionClassTest.php
test/unit/Reflection/ReflectionObjectTest.php
test/unit/Reflection/ReflectionPropertyTest.php

Would resolve #18 when complete.

Implement adapters for core reflection classes

---

src/Reflection/ReflectionProperty.php
test/unit/Reflection/ReflectionPropertyTest.php

Hotfix - #105 - default static variable are defaulted if declared

---

src/Reflection/ReflectionFunction.php
src/Reflection/ReflectionFunctionAbstract.php
test/unit/Reflection/ReflectionFunctionAbstractTest.php

Make ReflectionFunctionABstract#populateFunctionAbstract only accept specific nodes

---

src/Reflection/ReflectionClass.php
test/unit/Fixture/InheritedClassMethods.php
test/unit/Reflection/ReflectionClassTest.php

ReflectionClass#getMethods inheritance correction

---

src/SourceLocator/EvaledCodeSourceLocator.php
src/SourceLocator/PhpInternalSourceLocator.php
src/SourceLocator/SourceStubber.php
test/unit/Fixture/EmptyTrait.php
test/unit/SourceLocator/EvaledCodeSourceLocatorTest.php
test/unit/SourceLocator/PhpInternalSourceLocatorTest.php
test/unit/SourceLocator/SourceStubberTest.php

Hotfix - #119 - workaround for stubbing internal and evaluated sources

---

src/Reflector/Exception/IdentifierNotFound.php
test/unit/Reflector/Exception/IdentifierNotFoundTest.php

added identifier accessor for IdentifierNotFoundException

---

src/Reflection/ReflectionClass.php
src/Reflection/ReflectionObject.php
test/unit/Reflection/ReflectionClassTest.php

Includes update from master to merge #128

Digitalkaoz feature/immediate methods

---

README.md
composer.json
docs/compatibility.md
docs/usage.md
src/Reflection/Exception/InvalidAbstractFunctionNodeType.php
src/Reflection/ReflectionFunction.php
src/Reflection/ReflectionFunctionAbstract.php
src/Reflector/FunctionReflector.php
src/SourceLocator/Ast/Strategy/NodeToReflection.php
src/SourceLocator/Exception/TwoClosuresOneLine.php
src/SourceLocator/Type/ClosureSourceLocator.php
test/unit/Reflection/Exception/InvalidAbstractFunctionNodeTypeTest.php
test/unit/Reflection/ReflectionFunctionAbstractTest.php
test/unit/Reflection/ReflectionFunctionTest.php
test/unit/SourceLocator/Exception/TwoClosuresOneLineTest.php
test/unit/SourceLocator/Type/ClosureSourceLocatorTest.php

Handles issue #37 by adding ability to reflect on anonymous functions / closures.

Reflect from Closures

---

src/Reflection/ReflectionParameter.php
test/unit/Reflection/ReflectionParameterTest.php

Make sure variadic arguments are always optional

---

docs/usage.md
src/Reflection/ReflectionClass.php
src/Reflection/ReflectionMethod.php
src/Reflection/ReflectionParameter.php
src/Reflection/ReflectionProperty.php
test/unit/Fixture/ClassForHinting.php
test/unit/Reflection/ReflectionClassTest.php
test/unit/Reflection/ReflectionMethodTest.php
test/unit/Reflection/ReflectionObjectTest.php
test/unit/Reflection/ReflectionParameterTest.php
test/unit/Reflection/ReflectionPropertyTest.php

Added functions for static initialisation

---

composer.json

For #159 and 1.0.0 release in general

Updated require versions ready for 1.0.0 release

---

src/Reflection/ReflectionFunctionAbstract.php
src/Reflection/ReflectionParameter.php
src/Reflection/ReflectionType.php
src/SourceLocator/Type/SingleFileSourceLocator.php
test/unit/Fixture/Php7ParameterTypeDeclarations.php
test/unit/Fixture/Php7ReturnTypeDeclarations.php
test/unit/Reflection/ReflectionFunctionAbstractTest.php
test/unit/Reflection/ReflectionParameterTest.php
test/unit/Reflection/ReflectionTypeTest.php

Fixes #164 by implementing the stuff in the issue...

PHP 7 types support

---

README.md
docs/compatibility.md
docs/features.md
docs/types.md
src/Reflection/ReflectionParameter.php

Documentation for recently #176

Docs and phpdoc fixes for PHP 7 types

---

docs/compatibility.md
src/NodeCompiler/CompileNodeToValue.php
src/SourceLocator/Type/StringSourceLocator.php
test/unit/NodeCompiler/CompileNodeToValueTest.php

Completed implementation for failing test case from PR #167 (thanks @AydinHassan!)

Implemented ::class constant resolution 

---

demo/monkey-patching/index.php

It now works. It was borked before.

Fixed broken monkey patching example

---

src/Reflection/ReflectionClass.php
src/Reflection/ReflectionObject.php
test/unit/Reflection/ReflectionClassTest.php

Forms part of #134 and adds the following reflection modification methods:
* setFinal
* addMethod
* removeMethod
* addProperty
* removeProperty

ReflectionClass modifications

---

src/Reflection/ReflectionFunctionAbstract.php
test/unit/Reflection/ReflectionFunctionAbstractTest.php

As per #134, this adds new methods `ReflectionFunctionAbstract::addParameter` and `ReflectionFunctionAbstract::removeParameter`

Added addParameter and removeParameter methods

---

composer.json
src/TypesFinder/FindParameterType.php
src/TypesFinder/FindPropertyType.php
src/TypesFinder/FindReturnType.php
test/unit/TypesFinder/FindPropertyTypeTest.php

Upgrade phpdocumentor reflection docblock

---

src/SourceLocator/Located/LocatedSource.php
test/unit/SourceLocator/Located/LocatedSourceTest.php

LocatedSource now allows empty strings as source code

---

src/Reflector/FunctionReflector.php
test/unit/Reflector/FunctionReflectorTest.php

get all functions available in SourceLocator scope

---

src/TypesFinder/FindParameterType.php
src/TypesFinder/FindPropertyType.php
src/TypesFinder/FindReturnType.php
test/unit/TypesFinder/FindParameterTypeTest.php
test/unit/TypesFinder/FindPropertyTypeTest.php
test/unit/TypesFinder/FindReturnTypeTest.php

Types with no doc block

---

README.md

README: drop unstable dependencies reference

---

docs/usage.md

My first usage of this package in years. Let me know if there is another way

Usage: fix DirectoriesSourceLocator usage

---

docs/usage.md

Ref https://github.com/Roave/BetterReflection/pull/252
and https://github.com/Roave/BetterReflection/pull/253#issuecomment-290734337

[Docs] Usage - add FunctionReflector getAllFunctions() example

---

test/unit/Reflection/ReflectionClassTest.php

Fixes #204
Works already (as class constant visibility was added in PhpParser 3.0.0+ a while ago), no new reflection API (that I could find) to determine visibility of a class constant, so just added a test to ensure we get all class constants we expect, regardless of visibility.

Testing that class constant visibility works

---

src/Reflection/ReflectionMethod.php
test/unit/Fixture/UpperCaseConstructDestruct.php
test/unit/Reflection/ReflectionMethodTest.php

Added case insensitivity to isConstructor and isDestructor methods

---

src/Reflection/ReflectionClass.php
src/Reflection/ReflectionObject.php
test/unit/Fixture/InheritedClassProperties.php
test/unit/Reflection/ReflectionClassTest.php

getProperties returns inherited properties

---

demo/basic-reflection/example2.php

Just like their bros:
- https://github.com/Roave/BetterReflection/blob/master/demo/basic-reflection/example1.php
- https://github.com/Roave/BetterReflection/blob/master/demo/basic-reflection/example3.php

[docs] example2.php - flip fallen space from the bottom

---

demo/parsing-whole-directory/example1.php
demo/parsing-whole-directory/example2.php

Based on https://github.com/Roave/BetterReflection/issues/276#issuecomment-303426490

[demo] add getAllClasses() examples, ref #276

---

src/Reflection/ReflectionClassConstant.php
src/Reflection/ReflectionProperty.php
test/unit/Reflection/ReflectionClassConstantTest.php
test/unit/Reflection/ReflectionPropertyTest.php

The description is redundant :)

Added support for getStart/EndLine() for ReflectionClassConstant and ReflectionProperty

---

src/NodeCompiler/CompileNodeToValue.php
src/SourceLocator/Located/LocatedSource.php
src/Util/FileHelper.php
test/unit/NodeCompiler/CompilerContextTest.php
test/unit/SourceLocator/Located/LocatedSourceTest.php
test/unit/Util/FindHelperTest.php

Before:
```
Tests: 1670, Assertions: 29564, Errors: 1, Failures: 22, Skipped: 6.
```
Now:
```
Tests: 1673, Assertions: 29567, Errors: 1, Skipped: 7.
```

Fixed almost all tests on Windows

---

src/SourceLocator/Ast/FindReflectionsInTree.php
test/unit/SourceLocator/Ast/FindReflectionsInTreeTest.php

Needed for https://github.com/Roave/BetterReflection/pull/300

Improved AST traversing - all levels are inspected now

---

src/Reflection/ReflectionClass.php
src/Reflection/ReflectionMethod.php
test/unit/Fixture/Php4StyleCaseInsensitiveConstruct.php
test/unit/Fixture/Php4StyleConstruct.php
test/unit/Fixture/Php4StyleConstructInNamespace.php
test/unit/Reflection/ReflectionClassTest.php
test/unit/Reflection/ReflectionMethodTest.php

Fixed bug https://github.com/Roave/BetterReflection/issues/263

Support for PHP4 style constructors

---

.travis.yml
composer.json

#317 locking onto PHP 7.1 due to reflection API changes that cannot be made compatible with both versions

---

src/Reflection/ReflectionClass.php
src/Reflection/ReflectionClassConstant.php
src/Reflection/ReflectionFunctionAbstract.php
src/Reflection/ReflectionObject.php
src/Reflection/ReflectionParameter.php
src/Reflection/ReflectionProperty.php
src/SourceLocator/Ast/Locator.php
src/SourceLocator/Ast/PhpParserFactory.php
src/SourceLocator/Reflection/SourceStubber.php
src/SourceLocator/Type/AnonymousClassObjectSourceLocator.php
src/SourceLocator/Type/ClosureSourceLocator.php
src/Util/CalculateReflectionColum.php
src/Util/Exception/InvalidNodePosition.php
src/Util/Exception/NoNodePosition.php
test/unit/Reflection/ReflectionClassConstantTest.php
test/unit/Reflection/ReflectionClassTest.php
test/unit/Reflection/ReflectionFunctionAbstractTest.php
test/unit/Reflection/ReflectionObjectTest.php
test/unit/Reflection/ReflectionParameterTest.php
test/unit/Reflection/ReflectionPropertyTest.php
test/unit/SourceLocator/Ast/FindReflectionsInTreeTest.php
test/unit/SourceLocator/Ast/PhpParserFactoryTest.php
test/unit/Util/CalculateReflectionColumnTest.php
test/unit/Util/Exception/InvalidNodePositionTest.php
test/unit/Util/Exception/NoNodePositionTest.php

Implemented https://github.com/Roave/BetterReflection/issues/68

Implemented `getStartColumn()` and `getEndColumn()` methods

---

src/Reflection/Adapter/ReflectionMethod.php
src/Reflection/Adapter/ReflectionProperty.php
src/Reflection/ReflectionClass.php
src/Reflection/ReflectionMethod.php
src/Reflection/ReflectionObject.php
src/Reflection/ReflectionProperty.php
test/unit/Fixture/ClassWithMethodsAndTraitMethods.php
test/unit/Fixture/ClassWithPropertiesAndTraitProperties.php
test/unit/Reflection/Adapter/ReflectionMethodTest.php
test/unit/Reflection/Adapter/ReflectionPropertyTest.php
test/unit/Reflection/ReflectionMethodTest.php
test/unit/Reflection/ReflectionPropertyTest.php

Fix of https://github.com/Roave/BetterReflection/issues/327.

Adapters compatibility for properties and methods from traits

---

src/Reflection/Adapter/ReflectionType.php
test/unit/Reflection/Adapter/ReflectionTypeTest.php

Self and parent are not builtin types in internal reflection

---

stub/Exception.stub
test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php

#351 verify stub implemented interfaces and extended classes

---

composer.json

#334 bump `phpdocumentor/reflection-docblock` dependency version

---

src/NodeCompiler/CompileNodeToValue.php
src/Reflection/ReflectionClass.php
src/Reflection/ReflectionClassConstant.php
src/Reflection/ReflectionObject.php
src/Reflection/ReflectionProperty.php
test/unit/Reflection/ReflectionClassConstantTest.php
test/unit/Reflection/ReflectionClassTest.php
test/unit/Reflection/ReflectionPropertyTest.php

Fix of https://github.com/Roave/BetterReflection/issues/364

Fixed detection of all constants and properties defined by one keyword

---

stub/Closure.stub
test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php

Not sure hot to fix the failing test...

Improved Closure stub

---

src/Reflection/ReflectionParameter.php
test/unit/Reflection/ReflectionParameterTest.php

Other reflections already have this method.

Added ReflectionParameter::getAst()

---

src/Reflection/ReflectionClass.php
test/unit/Fixture/TraitFixture.php
test/unit/Reflection/ReflectionClassTest.php

Fix for https://github.com/Roave/BetterReflection/issues/398.

Method from trait renamed with alias should be available by the alias 

---

CONTRIBUTING.md
README.md
composer.json
src/Reflection/Adapter/ReflectionClassConstant.php
src/Reflection/ReflectionClass.php
src/Reflection/ReflectionFunction.php
src/Reflection/ReflectionType.php
src/SourceLocator/Type/AutoloadSourceLocator.php

Use HTTPS instead of HTTP

---

src/Reflection/ReflectionClass.php
src/Reflection/ReflectionFunctionAbstract.php
src/SourceLocator/Type/AggregateSourceLocator.php
test/unit/Fixture/ClassesWithPublicOrNonPublicContructor.php
test/unit/Reflection/ReflectionClassTest.php
test/unit/Reflection/ReflectionFunctionTest.php
test/unit/Reflector/ClassReflectorTest.php
test/unit/SourceLocator/Type/MemoizingSourceLocatorTest.php
test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php

Fix of https://github.com/Roave/BetterReflection/issues/411

Fixed ReflectionClass::isInstantiable() 

---

README.md
UPGRADE.md
docs/ast-extraction.md
docs/features.md
docs/find-reflection-on-line.md
docs/how-it-works.md
docs/reflection-modification.md
docs/types.md
docs/usage.md

- Removed weasel words like "simply", "just" and "easily"
- Reformatted to be 120 chars per line.
Pick your way through that 😆

Tidied docs and simply removed weasel words

---

test/unit/SourceLocator/Ast/Parser/MemoizingParserTest.php
test/unit/SourceLocator/Type/MemoizingSourceLocatorTest.php
test/unit/TypesFinder/FindParameterTypeTest.php
test/unit/TypesFinder/FindPropertyTypeTest.php
test/unit/TypesFinder/FindReturnTypeTest.php

Fixed build

---

src/Reflection/StringCast/ReflectionParameterStringCast.php

Use Null Coalesce Operator

---

src/Reflection/Adapter/ReflectionFunction.php
src/Reflection/Adapter/ReflectionMethod.php
src/Reflection/Adapter/ReflectionNamedType.php
src/Reflection/Adapter/ReflectionParameter.php
src/Reflection/ReflectionType.php
test/unit/Reflection/Adapter/ReflectionNamedTypeTest.php
test/unit/Reflection/Adapter/ReflectionTypeTest.php
test/unit/Reflection/ReflectionTypeTest.php

Fixes https://github.com/Roave/BetterReflection/issues/511
I hope it's backward compatible.

Added ReflectionNamedType adapter

---

psalm.xml
src/NodeCompiler/CompileNodeToValue.php
src/Reflection/Adapter/ReflectionClass.php
src/Reflection/Adapter/ReflectionClassConstant.php
src/Reflection/Adapter/ReflectionObject.php
src/Reflection/ReflectionClass.php
src/Reflection/ReflectionClassConstant.php
src/Reflection/ReflectionConstant.php
src/Reflection/ReflectionFunctionAbstract.php
src/Reflection/ReflectionObject.php
src/Reflection/ReflectionParameter.php
src/Reflection/ReflectionProperty.php
src/Reflection/StringCast/ReflectionConstantStringCast.php

Fix somes issues introduced in #531 (Just wait for CI to complete before merge, I'll check that Psalm is fixed)

fix windows path to linux + phpcbf

---

composer.json
composer.lock

Hi,
This PR upgrade `phpdocumentor/reflection-docblock` to version `5.0.0`.

Upgrade reflection-docblock to version ^5.0.0 and upgrade deps

---

src/Reflection/Adapter/ReflectionNamedType.php
src/Reflection/Adapter/ReflectionProperty.php
test/unit/Reflection/Adapter/ReflectionMethodTest.php
test/unit/Reflection/Adapter/ReflectionNamedTypeTest.php

Fixes #556 
Credit to @ondrejmirtes

Fixed ReflectionNamedType adapter

---

src/Reflection/ReflectionClass.php
src/Reflection/ReflectionMethod.php
test/unit/Fixture/TraitFixture.php
test/unit/Reflection/ReflectionClassTest.php

Fixed many traits bugs

---

src/Reflection/ReflectionClass.php
src/Reflection/StringCast/ReflectionClassConstantStringCast.php
test/unit/Reflection/ReflectionObjectTest.php
test/unit/SourceLocator/Type/AnonymousClassObjectSourceLocatorTest.php
test/unit/SourceLocator/Type/ClosureSourceLocatorTest.php
test/unit/SourceLocator/Type/PhpInternalSourceLocatorTest.php

Fixed hidden bugs

---

src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php

PhpStormStubsSourceStubber fixes for case-insensitive classes/functions/constants

---

src/SourceLocator/SourceStubber/PhpStormStubsSourceStubber.php
test/unit/SourceLocator/SourceStubber/PhpStormStubsSourceStubberTest.php

TRUE, FALSE, NULL constant names compatible with PHP

---

src/SourceLocator/SourceStubber/ReflectionSourceStubber.php

It's already called on line 433.

Removed duplicate ReflectionSourceStubber::addParameterModifiers() call

---

README.md

Removed broken build badge

---

README.md

Just adding a note into docs about using BR as just a drop-in replacement for native reflection (and why you wouldn't do that).

Added note about runtime reflection speed

---

src/Reflection/ReflectionFunctionAbstract.php
test/unit/Fixture/Methods.php
test/unit/Reflection/ReflectionClassTest.php
test/unit/Reflection/ReflectionParameterTest.php

Parameter with default value before variadic parameter should be optional

---

composer.json
composer.lock
src/SourceLocator/Type/Composer/Factory/MakeLocatorForInstalledJson.php
src/SourceLocator/Type/FileIteratorSourceLocator.php

duplicate of #669 with the needed fixes

Bump vimeo/psalm from 3.11.2 to 3.12.1

---

src/Reflection/Adapter/ReflectionClass.php
test/unit/Reflection/Adapter/ReflectionClassTest.php

Fix Adapter\ReflectionClass::$name
